### ISSUE TITLE
Arabic to Urdu Machine Translation

### ISSUE THREAD

**Issue by ghost** [lyeoni/nlp-tutorial#11]
@lyeoni 

In the case I want to train an Arabic to Urdu Machine Translation:
- is that attainable using this project?
- what options should be set in training?
- do you suggest another github project?

**Comment by lyeoni** [comment]
@deepseek 

- Is that attainable using this project?
>> I don't know. I've never seent Arabic-Urdu paired corpus dataset
- what options should be set in training?
>> It's up to your dataset size and resources. For example, If you have large corpus, I recommend to increase vocab_size (e.g. 30,000). and If you have many GPUs, I recommend to increase batch_size.
- do you suggest another github project?
>> for translation? I recommend .. pytorch translation tutorial. But It uses seq-to-seq model.
