### ISSUE TITLE
No module named 'nltk.tokenize.moses'

### ISSUE THREAD

**Issue by macrosea** [lyeoni/nlp-tutorial#2]
I had install nltk; but a error occur when I run the code;
```ModuleNotFoundError: No module named 'nltk.tokenize.moses'```

**Comment by lyeoni** [comment]
Hi @macrosea
Could you use the code below :) ?
```
$ pip install nltk==3.2.5
$ ipython
>>> import nltk
>>> nltk.download()
```

**Comment by Skvortsovg** [comment]
Hello @macrosea 

MosesTokenizer has been moved out of NLTK due to licensing issues.
You should install this `pip install mosestokenizer` nad replace your import from `from nltk.tokenize.moses import *` to from `mosestokenizer import *`

Also, you can use `sacremoses`. It is available via pip.
