### ISSUE TITLE
Movie Rating Classification no datasets

### ISSUE THREAD

**Issue by saigequn** [lyeoni/nlp-tutorial#4]
Movie Rating Classification no datasets?

**Comment by lyeoni** [comment]
@saigequn 
Hi, It might have a copyright issue.
If you wanna do classification task with movie reviews written this code,
I recommend using the crawler to crawl the reviews from https://movie.naver.com/

**Comment by lyeoni** [comment]
You can see this project ! 

[LINK] https://github.com/lyeoni/nlp-tutorial/tree/master/text-classification-transformer
[Description]
IMDb Movie Review Classification: This text classification tutorial trains a transformer model on the IMDb movie review dataset for sentiment analysis. It provides a simple PyTorch implementation, with simple annotation.
Keyword: Transformer, Sentiment analysis
