### ISSUE TITLE
Please add transformer based tutorial

### ISSUE THREAD

**Issue by thak123** [lyeoni/nlp-tutorial#8]
Kindly add a tutorial for NLP with transformer setup

**Comment by lyeoni** [comment]
@thak123,
I will soon upload IMDb Text Classification code using Transformer :)
If I updated, I will comment here again.
Thank you for your issue !

**Comment by lyeoni** [comment]
@thak123 
Hi ! Finally updated IMDb Text Classification task using Transformer.
Please visit below code :)
https://github.com/lyeoni/nlp-tutorial/tree/master/text-classification-transformer
